# Generated by Django 3.0.3 on 2020-03-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(default='Guarulhos', max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point',
            field=models.CharField(default='Shopping Internacional', max_length=50, verbose_name='Ponto de encontro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='full',
            field=models.BooleanField(default=False, verbose_name='Lotado'),
        ),
    ]
