# Generated by Django 3.0.3 on 2020-03-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200310_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('Natureza', 'Natureza'), ('Cultural', 'Cultural'), ('Aventura', 'Aventura')], max_length=50, verbose_name='Tipo'),
        ),
    ]
