# Generated by Django 3.0.3 on 2020-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200310_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='sold',
        ),
        migrations.AddField(
            model_name='tour',
            name='available',
            field=models.PositiveIntegerField(default=5, verbose_name='Disponíveis'),
            preserve_default=False,
        ),
    ]
