# Generated by Django 3.0.3 on 2020-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200310_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='tour',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Capacidade'),
            preserve_default=False,
        ),
    ]
